# alertmanager.yml

global:
  resolve_timeout: 1m

route:
  receiver: mattermost
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
    
receivers:
  - name: mattermost
    mattermost_configs:
      - webhook_url: "https://meeting.ssafy.com/hooks/ya15aeabtjfxip36uyf1ibh77a"
        text: '[ {{ .Status | toUpper }} | {{ .CommonLabels.severity }} ] : {{ .CommonLabels.alertname }}'
        # channel / username / icon_url / icon_emoji / attachments / props / priority 등도 가능
